---
title: "CodeBook"
author: "Fiona Falzon"
date: "18 September 2015"
output: html_document
---

#SummarizedHARData.txt
This is a consolidation of the **Human Activity Recognition Using Smartphones Data Set**
<http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones>

Mean and Standard deviation data from Test and Training data has been merged, and summarized to give the mean of these measurements.
Measurements 3 to 88 are the normalized and bounded within [-1,1]


The data set contains 180 obs. of  88 variables

1. Activity                             : Factor w/ 6 levels "LAYING","SITTING",..: 4 4 4 4 4 4 4 4 4 6 ...
- Factors : "WALKING","WALKING_UPSTAIRS","WALKING_DOWNSTAIRS","SITTING","STANDING","LAYING" 

2. Subject                              : Factor w/ 30 levels "1","2","3","4",..: 2 4 9 10 12 13 18 20 24 2 ...
- Factors : "1","2","3" ... "30" representing the 30 participants in the study


3. tBodyAcc.mean...X                    : num  0.276 0.279 0.279 0.279 0.277 ...
4. tBodyAcc.mean...Y                    : num  -0.0186 -0.0148 -0.0181 -0.017 -0.0156 ...
5. tBodyAcc.mean...Z                    : num  -0.106 -0.111 -0.111 -0.109 -0.103 ...
6. tGravityAcc.mean...X                 : num  0.913 0.964 0.952 0.963 0.967 ...
7. tGravityAcc.mean...Y                 : num  -0.3466 -0.0859 -0.0314 -0.0838 -0.156 ...
8. tGravityAcc.mean...Z                 : num  0.0847 0.1278 -0.1159 0.0549 -0.0361 ...
9. tBodyAccJerk.mean...X                : num  0.0618 0.0784 0.0704 0.0858 0.0458 ...
10. tBodyAccJerk.mean...Y               : num  0.01825 0.00296 0.02123 0.00408 0.01978 ...
11. tBodyAccJerk.mean...Z               : num  0.007895 -0.000768 0.004148 -0.016295 0.005026 ...
12. tBodyGyro.mean...X                  : num  -0.053 -0.0318 -0.0808 0.0107 -0.1045 ...
13. tBodyGyro.mean...Y                  : num  -0.0482 -0.0727 -0.0626 -0.082 -0.0344 ...
14. tBodyGyro.mean...Z                  : num  0.0828 0.0806 0.1116 0.0987 0.1 ...
15. tBodyGyroJerk.mean...X              : num  -0.0819 -0.1153 -0.0809 -0.1227 -0.0622 ...
16. tBodyGyroJerk.mean...Y              : num  -0.0538 -0.0393 -0.0356 -0.0519 -0.0499 ...
17. tBodyGyroJerk.mean...Z              : num  -0.0515 -0.0551 -0.0633 -0.0611 -0.0467 ...
18. tBodyAccMag.mean..                  : num  -0.2904 -0.3121 -0.0981 -0.1274 -0.1022 ...
19. tGravityAccMag.mean..               : num  -0.2904 -0.3121 -0.0981 -0.1274 -0.1022 ...
20. tBodyAccJerkMag.mean..              : num  -0.281 -0.367 -0.204 -0.133 -0.144 ...
21. tBodyGyroMag.mean..                 : num  -0.447 -0.498 -0.295 -0.156 -0.356 ...
22. tBodyGyroJerkMag.mean..             : num  -0.548 -0.681 -0.51 -0.44 -0.517 ...
23. fBodyAcc.mean...X                   : num  -0.346 -0.4267 -0.2947 -0.1142 -0.0544 ...
24. fBodyAcc.mean...Y                   : num  -0.0219 -0.1494 -0.2577 0.0534 -0.0713 ...
25. fBodyAcc.mean...Z                   : num  -0.454 -0.631 -0.251 -0.412 -0.422 ...
26. fBodyAcc.meanFreq...X               : num  -0.146 -0.139 -0.311 -0.263 -0.261 ...
27. fBodyAcc.meanFreq...Y               : num  0.1986 0.0123 0.0213 0.2438 0.1491 ...
28. fBodyAcc.meanFreq...Z               : num  0.0689 -0.0788 0.0238 0.259 0.1708 ...
29. fBodyAccJerk.mean...X               : num  -0.3046 -0.3589 -0.3143 -0.1079 -0.0816 ...
30. fBodyAccJerk.mean...Y               : num  -0.0788 -0.2796 -0.3677 0.0309 -0.1414 ...
31. fBodyAccJerk.mean...Z               : num  -0.555 -0.729 -0.4 -0.464 -0.491 ...
32. fBodyAccJerk.meanFreq...X           : num  -0.0727 -0.1353 -0.3783 -0.2601 -0.2811 ...
33. fBodyAccJerk.meanFreq...Y           : num  -0.264 -0.386 -0.389 -0.148 -0.223 ...
34. fBodyAccJerk.meanFreq...Z           : num  -0.2548 -0.3257 -0.3666 0.0558 -0.182 ...
35. fBodyGyro.mean...X                  : num  -0.43 -0.373 -0.384 -0.278 -0.402 ...
36. fBodyGyro.mean...Y                  : num  -0.555 -0.688 -0.437 -0.345 -0.468 ...
37. fBodyGyro.mean...Z                  : num  -0.397 -0.601 -0.24 -0.109 -0.317 ...
38. fBodyGyro.meanFreq...X              : num  0.00728 -0.12715 -0.20062 -0.09337 0.02041 ...
39. fBodyGyro.meanFreq...Y              : num  -0.0427 -0.2747 0.0165 -0.1221 -0.0255 ...
40. fBodyGyro.meanFreq...Z              : num  0.1398 0.1499 -0.1521 -0.1298 -0.0279 ...
41. fBodyAccMag.mean..                  : num  -0.324 -0.451 -0.319 -0.093 -0.153 ...
42. fBodyAccMag.meanFreq..              : num  0.393 0.382 0.162 0.18 0.252 ...
43. fBodyBodyAccJerkMag.mean..          : num  -0.1691 -0.3186 -0.3169 0.0205 -0.0299 ...
44. fBodyBodyAccJerkMag.meanFreq..      : num  0.2075 0.1115 0.1592 -0.0713 0.0184 ...
45. fBodyBodyGyroMag.mean..             : num  -0.531 -0.609 -0.514 -0.413 -0.443 ...
46. fBodyBodyGyroMag.meanFreq..         : num  0.3053 0.0697 0.1274 0.1291 0.1461 ...
47. fBodyBodyGyroJerkMag.mean..         : num  -0.583 -0.724 -0.603 -0.515 -0.561 ...
48. fBodyBodyGyroJerkMag.meanFreq..     : num  0.126345 0.265355 0.243222 -0.000234 0.077778 ...
49. angle.tBodyAccMean.gravity.         : num  -0.0301 -0.012 -0.026 -0.0198 0.045 ...
50. angle.tBodyAccJerkMean..gravityMean.: num  0.053401 0.000921 0.062348 -0.042832 0.016085 ...
51. angle.tBodyGyroMean.gravityMean.    : num  0.0216 0.0178 0.1213 -0.1253 0.1755 ...
52. angle.tBodyGyroJerkMean.gravityMean.: num  -0.0858 0.0554 -0.0266 0.0991 -0.0973 ...
53. angle.X.gravityMean.                : num  -0.662 -0.865 -0.845 -0.858 -0.86 ...
54. angle.Y.gravityMean.                : num  0.321 0.143 0.105 0.141 0.19 ...
55. angle.Z.gravityMean.                : num  -0.0369 -0.0675 0.1038 -0.0166 0.0468 ...
56. tBodyAcc.std...X                    : num  -0.424 -0.441 -0.238 -0.179 -0.129 ...
57. tBodyAcc.std...Y                    : num  -0.0781 -0.0788 -0.2017 -0.0227 -0.1228 ...
58. tBodyAcc.std...Z                    : num  -0.425 -0.586 -0.058 -0.396 -0.411 ...
59. tGravityAcc.std...X                 : num  -0.973 -0.984 -0.981 -0.974 -0.979 ...
60. tGravityAcc.std...Y                 : num  -0.972 -0.968 -0.971 -0.971 -0.965 ...
61. tGravityAcc.std...Z                 : num  -0.972 -0.963 -0.956 -0.958 -0.95 ...
62. tBodyAccJerk.std...X                : num  -0.2775 -0.297 -0.2067 -0.0522 -0.0135 ...
63. tBodyAccJerk.std...Y                : num  -0.0166 -0.2212 -0.2769 0.0751 -0.0894 ...
64. tBodyAccJerk.std...Z                : num  -0.586 -0.751 -0.41 -0.512 -0.512 ...
65. tBodyGyro.std...X                   : num  -0.562 -0.501 -0.476 -0.414 -0.546 ...
66. tBodyGyro.std...Y                   : num  -0.538 -0.665 -0.467 -0.251 -0.449 ...
67. tBodyGyro.std...Z                   : num  -0.481 -0.663 -0.266 -0.175 -0.35 ...
68. tBodyGyroJerk.std...X               : num  -0.39 -0.492 -0.527 -0.366 -0.391 ...
69. tBodyGyroJerk.std...Y               : num  -0.634 -0.807 -0.549 -0.51 -0.581 ...
70. tBodyGyroJerk.std...Z               : num  -0.435 -0.64 -0.458 -0.329 -0.481 ...
71. tBodyAccMag.std..                   : num  -0.423 -0.528 -0.379 -0.186 -0.237 ...
72. tGravityAccMag.std..                : num  -0.423 -0.528 -0.379 -0.186 -0.237 ...
73. tBodyAccJerkMag.std..               : num  -0.1642 -0.3169 -0.3171 0.0376 -0.0203 ...
74. tBodyGyroMag.std..                  : num  -0.553 -0.553 -0.49 -0.402 -0.413 ...
75. tBodyGyroJerkMag.std..              : num  -0.558 -0.73 -0.6 -0.501 -0.549 ...
76. fBodyAcc.std...X                    : num  -0.458 -0.447 -0.218 -0.206 -0.161 ...
77. fBodyAcc.std...Y                    : num  -0.169 -0.102 -0.224 -0.13 -0.209 ...
78. fBodyAcc.std...Z                    : num  -0.4552 -0.5942 -0.0338 -0.4353 -0.4521 ...
79. fBodyAccJerk.std...X                : num  -0.3143 -0.2973 -0.1702 -0.0792 -0.0311 ...
80. fBodyAccJerk.std...Y                : num  -0.0153 -0.2099 -0.2284 0.0485 -0.0941 ...
81. fBodyAccJerk.std...Z                : num  -0.616 -0.772 -0.419 -0.559 -0.531 ...
82. fBodyGyro.std...X                   : num  -0.604 -0.543 -0.507 -0.458 -0.593 ...
83. fBodyGyro.std...Y                   : num  -0.533 -0.655 -0.491 -0.204 -0.444 ...
84. fBodyGyro.std...Z                   : num  -0.56 -0.716 -0.342 -0.273 -0.422 ...
85. fBodyAccMag.std..                   : num  -0.577 -0.651 -0.514 -0.37 -0.409 ...
86. fBodyBodyAccJerkMag.std..           : num  -0.1641 -0.3205 -0.3223 0.0502 -0.014 ...
87. fBodyBodyGyroMag.std..              : num  -0.652 -0.594 -0.563 -0.5 -0.495 ...
88. fBodyBodyGyroJerkMag.std..          : num  -0.558 -0.758 -0.624 -0.518 -0.565 ...




